### ISSUE TITLE
255 Site Build Error

### ISSUE THREAD

**Issue by remysheppard** [NormandErwan/blogpaper#8] opened 2020-01-14 23:39 UTC
I traced back the bug and this was the only error during the build:

 Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:3:7: executing "main" at <partial "header" .>: error calling partial: "/opt/build/repo/themes/Blogpaper/layouts/partials/header.html:23:55": execute of template failed: template: partials/header.html:23:55: executing "partials/header.html" at <$.RenderString>: can't evaluate field RenderString in type *hugolib.pageState

When I remove the subtitle code completely everything builds. 

What's interesting is I only run into this error when building using netlify. When I build locally it works fine.

**Comment by NormandErwan** [comment] 2020-01-15 18:24
The error is caused by the [`.RenderString`](https://gohugo.io/functions/renderstring/) function which is new since [Hugo 0.62](https://gohugo.io/news/0.62.0-relnotes/) in date of December 2019.

I switched to another function which is supported by more Hugo versions.

Can you try again with the latest version of the theme?

**Comment by remysheppard** [comment] 2020-01-15 23:41
Works perfect with Forestry/Netlify/Gitlab. That solved it. Thanks!

**Comment by NormandErwan** [comment] 2020-01-16 09:12
Glad it works! I'm closing this ticket.

**Closed as completed by NormandErwan** 2020-01-16 09:12 UTC
